name: online_payments_flutter_example
description: Flutter application demonstrating how to use the Online Payments Flutter SDK
version: 1.0.1

publish_to: 'none'

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  online_payments_sdk: ^1.3.2

  online_payments_repository:
    path: packages/online_payments_repository

  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  collection: ^1.19.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.10
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
